### ISSUE TITLE
Script force closes

### ISSUE THREAD

**Issue by ghost** [Mandruyd/HQ-Token#1]
Basically that, the script automatically closes after introducing either an invalid number (which is a random error) or after I enter the SMS code.

**Comment by Mandruyd** [comment]
Try running it within cmd and give me the error code/and/or message.

**Comment by Lardi154** [comment]
That's the problem, CMD opens, I type phone, SMS code, and it gives me the token for a split second before the window closes.

**Comment by Lardi154** [comment]
[Video](https://youtu.be/O7zYLh4AL8w)
